### ISSUE TITLE
love build fails to fully decompress love-12.0-macos.zip

### ISSUE THREAD

**Issue by Endaris** [ellraiser/love-build#4]
When trying to build for love 12.0 on mac, love-build crashes with

```
Error

love-build.lua:415: attempt to perform arithmetic on local 'types' (a nil value)

Traceback

[love "callbacks.lua"]:239: in function 'handler'
love-build.lua:415: in function 'next'
main.lua:57: in function 'update'
[love "callbacks.lua"]:174: in function <[love "callbacks.lua"]:156>
[C]: in function 'xpcall'
```
As far as I can tell, `Info.plist` does not actually get decompressed but stays in the zipped format so all the xml related operations fail.

**Comment by ellraiser** [comment]
Artifacts on Github are compressed twice - when you download the macos source for 12 from Github, you need to unzip it first, and then rezip it. This is because actually the macos.zip artifact is a zip of the .app

MacOS 'helpfully' unzips twice for you when you do it manually yourself so it doesn't seem like it's the case, but you can tell by running the following command on the zip when you download it:
`unzip -vl PATH/TO/macos.zip`
You'll see the contents IS a zip file, vs when you rezip the .app you'll see the app as the contents.

If this was a issue the workflow would crash, as the builder itself is built with 12.0 - you can see in the yaml that I unzip twice here:
https://github.com/ellraiser/love-build/blob/main/.github/workflows/main.yaml#L26

**Comment by DPS2004** [comment]
I'm unfortunately getting the same issue on Windows even after removing the outer layer of zip.
[love build log.txt](https://github.com/user-attachments/files/16385408/love.build.log.txt)

**Comment by ellraiser** [comment]
Sounds like you're not using a valid 12.0 zip - the only thing that should be inside is the love-12.app at the root

**Comment by DPS2004** [comment]
It looks like in the latest workflow run the folder is actually named just `love.app` .
The directory tree looks like:
```
love-macos.zip
|_ love-macos.zip
   |_ love.app
      |_ contents
```

After making a zip that only has love-12.app in the root, I now get this:

[love build log 2.txt](https://github.com/user-attachments/files/16402031/love.build.log.2.txt)

**Comment by ellraiser** [comment]
Yes it will be called `love.app` sorry - was just specifying the version.

Using the latest successful `love-macos` artifact from love-main, unzipping the double zip and rezipping and putting in the love-build/cache folder I get a successful build process - [build.log](https://github.com/user-attachments/files/16409621/build.log)

The zip used - [love-12.0-macos.zip](https://github.com/user-attachments/files/16409626/love-12.0-macos.zip)

Not sure what else would prevent it if the setup is right, unless for some reason you dont have permission to access the zip.

**Comment by DPS2004** [comment]
Weird, for some reason that zip you posted works? Maybe my setup is just haunted... Either way, thanks for helping me troubleshoot this
